### ISSUE TITLE
Does this work with Azrue DevOps?

### ISSUE THREAD

**Issue by manfred0191** [github-changelog-generator/github-changelog-generator#1044]
Or only with github ??

**Comment by olleolleolle** [comment]
Thanks for asking. Short answer: only with GitHub.

Longer answer:

The features of this program relies on [the GitHub REST API](https://docs.github.com/en/rest?apiVersion=2022-11-28).

That API is also implemented as an on-prem for-pay service big organizations can run on their own infrastructure. [See GitHub's overview docs](https://docs.github.com/en/enterprise-server@3.12/admin/overview/about-github-enterprise-server).

Hope this helps!
