### ISSUE TITLE
replace github_api to octokit

### ISSUE THREAD

**Issue by tuexss** [github-changelog-generator/github-changelog-generator#222]
I think it would be good to remove the whole regex-mess and use some third-party-library like https://github.com/octokit/octokit.rb to do this in a short and clean way.

**Comment by skywinder** [comment]
What kind of "regex-mess" are you meaning?

About third-party library - I agree with you. 
I get in mind to replace `github_api` to `octokit`. To work with GitHub API.
I also want to do it once:
- move all functions with API operations in separate class (like `fetcher.rb` or smth like that)
- cover it by tests
- replace `github_api` to `octokit`

Just don't have a time for it yet. :stuck_out_tongue_closed_eyes:

**Comment by tuexss** [comment]
I meant the fact, that there are three different regexes and a bunch of logic to manage the three in parser.rb, when it only parses a single string in order to extract user and project.

**Comment by tuexss** [comment]
Sounds like a good plan.

**Comment by skywinder** [comment]
Got it. Yes, it was my first experience with regex on ruby. :smile:

**Comment by mvz** [comment]
This gem now uses octokit, so I think this ticket can be closed.

**Comment by olleolleolle** [comment]
Thanks all!
