### ISSUE TITLE
Add more Collaborators to GitHub Changelog Generator

### ISSUE THREAD

**Issue by skywinder** [github-changelog-generator/github-changelog-generator#272]
I want other people to feel like they own GitHub Changelog Generator, too, so it help in the long run.

What I'm looking for is people who can:
- Reply to questions.
- Help diagnose/fix issues people have.
- Help form a roadmap for future releases.

All when you have time and feel like it. It's not meant to be a burden.

> Don't ever feel bad for not contributing to open source. —@alloy

Thanks to @searls for the push to do this by [this talk](http://blog.testdouble.com/posts/2014-12-02-the-social-coding-contract.html). 

If you're interested in helping out – when it's convenient for you – comment on this issue and I'll add you as a committer with push access.

Cheers! :smile: :computer: :earth_africa:

/cc @raphink @estahn @tuexss @sneal @sue445 @glenlovett @sildur @dlanileonardo @olleolleolle

**Comment by raphink** [comment]
Very interesting video :smile:

**Comment by olleolleolle** [comment]
I'd be interested in caring for this library as a Collaborator. Thanks for the trust.

**Comment by dlanileonardo** [comment]
I'm interested in collaborate.

**Comment by olleolleolle** [comment]
@thorsteneckel, would this be something for you?

**Comment by thorsteneckel** [comment]
Oh :) Would be an honor!

**Comment by olleolleolle** [comment]
Poke, poke, @skywinder - can you add @thorsteneckel as a "collaborator"?

**Comment by skywinder** [comment]
@olleolleolle  With pleasure under your supervision! 😉   👍
Welcome, @thorsteneckel! 🎉

**Comment by thorsteneckel** [comment]
thanks guys 🤓  glad to be here 🎉

**Comment by m1guelpf** [comment]
Would be interested to help :smile:

**Comment by Lucashuang0802** [comment]
I would love to be part of it. @skywinder @olleolleolle 😄

**Comment by skywinder** [comment]
Hey. that was an awesome time. Thanks to everyone , who participated in this project. Let's keep it alive together. Updates are here: #727
