### ISSUE TITLE
Add support for custom sections

### ISSUE THREAD

**Issue by SandroMachado** [github-changelog-generator/github-changelog-generator#316]
Currently the project groups the `merged` pull-requests, the issues with the label `bug` and the issues with the label `enhancement`. All the issues with other labels are grouped at the same block. 

Is it possible to add more labels to group the issues with that labels?  

Thanks for your work.

**Comment by skywinder** [comment]
No, there is no such option yet.

**Comment by ruipenso** [comment]
:+1:

**Comment by olleolleolle** [comment]
(In order to know more about the feature, here's a guess about how it could be used.)

> Randy the Rake-User wants to group cool new stuff under a release notes Section named "Goodies in this release", which lists any `merged` pull-request which has the label `goodies` or the label `wonderful`.

> He introduces this new section by amending his Rake task definition:

```ruby
config.custom_sections << ['Goodies in this release', %w(goodies wonderful)]
```

**Comment by skywinder** [comment]
@olleolleolle :+1: 

or by command line smth like:
`--custom_sections 'Goodies in this release', goodies, wonderful`

But how to make ability to add several custom sections? 
Obviously, we have to create internal Dictionary `[String:Array]`
like 
```
{
"Bugs" : [bug, Bug, another Bug Label],
"Features" : [feature, improvement],
...
}

```

Do you know convenient way to add it via CLI options?

**Comment by ruipenso** [comment]
@skywinder Any news? :)

**Comment by skywinder** [comment]
@ruipenso didn't work on that feature yet.

**Comment by aerosol** [comment]
Just came here to give big ups :100:. Being able to group the changes per custom labels, e.g. "API" and "Front-End" would be totally awesome.

The CLI interface could look like:

```
--custom-group-{name}-labels=foo,bar,baz
```

e.g.

```
--custom-group-api-labels=api --custom-group-frontend-labels=web,javascript
```

This way you could easily (sorry if I'm underestimating this - I'm not fluent with ruby at all), build the hierarchy - first build the custom groups, then within those, build the log of bugs, enhancements etc.

**Comment by skywinder** [comment]
@aerosol how to solve several groups in that case?

**Comment by aerosol** [comment]
@skywinder could you give an example?

**Comment by nicwaller** [comment]
I would also appreciate this feature! In accordance with [Semantic Versioning](http://semver.org/) I make a point of highlighting changes that break backward compatibility. It would be great if I could configure the changelog generator to include a section for breaking changes. Like this.

```
--section 'Breaking Changes #breaking' --section 'Deprecated #deprecated'
```

As you can see, I've also proposed an alternate command line syntax for specifying sections. I like the idea of being able to specify the `--section` option more than once. I've seen precedent for this in other tools, but can't cite an example right now. I've also suggested using a hashtag syntax to identify relevant labels, but that has two problems. First, it is messy and unintuitive. Second, it doesn't support labels with spaces in their names.

**Comment by aih** [comment]
An alternate, or additional feature would be to add the label next to the commit message. Something like:

- Add support for custom sections #313 [feature-request]

**Comment by crtrott** [comment]
Just wanted to add that we'd like to see this feature as well. But its a great tool already.

**Comment by stratosgear** [comment]
As @nicwaller mentioned above, the ability to hilight breaking changes in this newer release, is sorely needed in my use case.

Regarding passing multiple "sections", again as nicwaller suggests you could use repeating --section options.   Don't know the state of command line parsing libraries in Ruby, but several in Python allow you to easily implement that.

Great tool by the way... :)

**Comment by srizzling** [comment]
with regards to this. I would like to add a section that has some list of artifacts (AMIs) in my case attached to each release. Is there someway I can add that?

**Comment by skywinder** [comment]
@srizzling Yep. It's a super cool and most required feature.

I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍

**Comment by dusan-dragon** [comment]
I guess this is supported already by option `configure-sections` ?

**Comment by stephenpmurray** [comment]
Can anyone confirm whether the `configure-sections` option actually works at the moment, or whether this is a WIP feature?

**Comment by dusan-dragon** [comment]
@stephenpmurray `configure-sections` works for us in our project

**Comment by stephenpmurray** [comment]
@dusan-dragon Thanks for the quick reply. At the risk of hijacking this thread, do you have an example of this being used? I have added the following to `.github_changelog_generator`:
```
add-sections= { "name": "dependencies", "prefix": "**Dependency Changes**", "labels": [ "dependency", "Dependency" ]  }
```
But am recieving the following error:
`entry.rb:75:in `block in parse_sections' : no implicit conversion of String into Integer`
An issue of JSON string parsing, perhaps?

**Comment by dusan-dragon** [comment]
@stephenpmurray as I wrote I am not sure about `add-section`, instead we defined all sections via `configure-sections`

This works for us:
```
configure-sections={"summary": {"prefix": "**Update notes**", "body_only": true, "labels": ["release-summary"]}, "new_features": {"prefix": "**New features**","labels": ["enhancement"]},"deprecated": {"prefix": "**Deprecated**","labels": ["deprecated"]},"bug_fixes": {"prefix": "**Bug fixes**","labels": ["bug"]},"critical": {"prefix": "**Critical updates**","labels": ["critical"]},"breaking_changes": {"prefix": "**Breaking changes**","labels": ["breaking"]}}
```

**Comment by stephenpmurray** [comment]
@dusan-dragon Thanks for the help, that's working for me, and I can confirm that `add-sections` is working with the above format. 

Would it be helpful if I open a PR adding an example to the README?
