### ISSUE TITLE
Cache API responses

### ISSUE THREAD

**Issue by gravitystorm** [github-changelog-generator/github-changelog-generator#361]
From https://github.com/skywinder/github-changelog-generator/issues/71#issuecomment-200343511

It would be a good idea to cache the API responses (e.g. issues and PRs) to save downloading them again every time that github_changelog_generator is run.

This is a major problem for the project that I'm working on (https://github.com/gravitystorm/openstreetmap-carto) due to the moderately large number of issues and PRs (1322 and 773 so far). It is taking me a while just to implement our initial changelog, since I need to change issue tags, change config values, run github_changelog_generator again to see the results - and then I rapidly run out of API requests. In the future I will run out of API requests before the changelog can be generated just once!

Also, it takes a long time to download all the issues, so iterating our config values is painful.

I investigated the github API briefly. The list of issues (e.g. https://api.github.com/repos/gravitystorm/openstreetmap-carto/issues ) contains last-updated timestamps, so it seems possible to cache the details and only update when the timestamp changes. Do you think this would work? This way, repeated runs of github_changelog_generator would be faster and involve fewer API requests.

**Comment by skywinder** [comment]
Agree, as @estahn mentioned:

> Use [octokit/octokit.rb](https://github.com/octokit/octokit.rb) with [Faraday HTTP Cache](https://github.com/octokit/octokit.rb#caching) 

could be nice alternative to #211.

**Comment by retorquere** [comment]
I've started doing this on a fork

**Comment by retorquere** [comment]
Not a simple change. I'm a little lost in how GCG hangs together, to be honest.

I have Octokit-based caching working, but care needs to be taken when it comes to thread-safety, and the objects Octokit yields are subtly different it seems, and the github_api objects are passed around the app, so a move to octokit touches nearly everything at once.

I'm doing some sqlite-based experiments (my current cache is sqlite -- I know about the earlier objections, but I still haven't found a good replacement), and it just struck me that GCG could probably be simplified by stashing the fetched data in sqlite, too. Filtering and matching is what databases are good at, and you get a more loose coupling internally as everything would get back hashes from the DB.

Just a thought.

**Comment by skywinder** [comment]
@retorquere :+1: 
please give me name of your branch and push it in your fork to review!

To simplify this feature, I would like to finish #222 first. I want to do it this week, so it will easier to implement this feature after!

**Comment by retorquere** [comment]
There's no branch yet. Nothing works right now.

**Comment by mikewaters** [comment]
+1'd, we have 6k pull requests and the generator parses them *all*, even if I only want the current release. I'd like to integrate this with our CD, and don't want to run into API limitations (or knock over our enterprise instance).

**Comment by cyberw** [comment]
Is this (at least partially) fixed by #422 ?

**Comment by skywinder** [comment]
@cyberw you're right . it already fixed by great work of @olleolleolle . So I will close this issue
