### ISSUE TITLE
[wishlist] --include-tags-regex

### ISSUE THREAD

**Issue by yarikoptic** [github-changelog-generator/github-changelog-generator#376]
There is `--exclude-tags-regex` but there could be a variety of non-release tags in the repository.  So IMHO it would be a more common use-case to be able to specify which tags regex to consider (instead of trying to catch all the ones to exclude).  Or is there a "negation" which could be specified within exclude-tags-regex, so I could say "exclude all which do not match this regex".  Thanks in advance

**Comment by donquixote** [comment]
Yes please!
Typical use case:
- include semver tags with include-tags-regex
- exclude specific semver tags with exclude-tags-regex

**Comment by donquixote** [comment]
Fixed by #929 ?
