### ISSUE TITLE
What is the expected behavior of "between-tags"?

### ISSUE THREAD

**Issue by tduffield** [github-changelog-generator/github-changelog-generator#450]
The wording of the description of "between-tags" says that the "Change log will be filled only between specified tags". What I took that to mean was that if I specified tags, the section headers would combine the changelog for those tags. 

For example, say I have the following tags: 1.2.[0-20], 1.3.[0-40], and 1.4.[0-10]. 
Now, lets say that I specify the following config: 
```
since-tag=1.2.0
between-tags=1.2.12,1.2.34,1.3.15,1.4.10
```

I would expect the following:

```
# 1.4.10
compare/1.3.16...1.4.10

# 1.3.15
compare/1.2.35...1.3.15

# 1.2.34
compare/1.2.13...1.2.34

# 1.2.12
compare/1.2.0...1.2.12
```

But instead, I get the following:

```
# 1.4.10
compare/1.4.9...1.4.10

# 1.3.15
compare/1.3.14...1.3.15

# 1.2.34
compare/1.2.33...1.2.34

# 1.2.12
compare/1.2.11...1.2.12
```

Which of these two is the expected behavior?

**Comment by tduffield** [comment]
Sorry @olleolleolle, but it'd be great if I can have an answer in the next couple days. I have some time-sensitive work that depends on the answer.

**Comment by olleolleolle** [comment]
I have not investigated `--between-tags`. Not sure what it wants to do. The actual behavior seems not-so-useful, though.

@skywinder, do you know? 

@tduffield If you feel like poking through the history and deduce, it's all there.

**Comment by tduffield** [comment]
@olleolleolle I did look through the history briefly but I didn't see anything that answered my question super clearly.

**Comment by skywinder** [comment]
The `--between-tags` not pretty useful and quite outdated option.
It works like `filter` for tags. i.e. leave tags, that specified after this option.
I think we can remove it in next major release to simplify the code.

**Comment by tduffield** [comment]
I have to disagree. The between-tags is super useful for us (given my PR) in that we bump the version after every PR automatically but want the change log to reflect stable "releases." Im down if we want to deprecate that but having a way to specify section groupings is a must for us.

**Comment by Lucashuang0802** [comment]
The `--between-tags` will be removed on the next release, @olleolleolle so this is not an issue anymore? 😃
