### ISSUE TITLE
Milestones on PRs not taken into account

### ISSUE THREAD

**Issue by Turbo87** [github-changelog-generator/github-changelog-generator#457]
I've tried to regenerate the changelog on https://github.com/ember-cli/ember-cli-mocha, but seems to ignore the milestones set on some of the PRs.

e.g. https://github.com/ember-cli/ember-cli-mocha/pull/134 has milestone `v0.13.0` but generating the changelog puts it under the `v0.12.0` release instead.

```
$ github_changelog_generator --version
Version: 1.14.1
```

**Comment by olleolleolle** [comment]
filter_by_milestone feature option is used here: https://github.com/skywinder/github-changelog-generator/blob/d551c3a1987f34f6d1b20e2c35bcdf52b9a827ab/lib/github_changelog_generator/generator/generator_generation.rb#L103

**Comment by Turbo87** [comment]
```
github_changelog_generator --future-release v0.13.0
```

and

```
github_changelog_generator --future-release v0.13.0 --filter-by-milestone
```

both result in the same and wrong result. Removing the `--future-release` option also doesn't have any effect aside from changing the future release name as expected.

**Comment by Turbo87** [comment]
@olleolleolle I should probably add that the option seems to work fine for issues, but it does not work for PRs

**Comment by Turbo87** [comment]
@olleolleolle I have debugged this further and it seems that `--future-release` is indeed responsible for the problem, or rather it doesn't work as I would expect it.

Milestones are taken into account for all git tags, but the milestone that matches the `--future-release` isn't. In other words: if you try the changelog generator on the repository linked above it will work right as expected because the `v0.13.0` is tagged and released now. If you try it with e.g. a `--future-release v0.14.0` and have a `v0.14.0` milestone with PRs in it, those PRs might not necessarily be assigned to the correct release by the generator.
