### ISSUE TITLE
bundler 1.14.3 issue with  uninitalized constant

### ISSUE THREAD

**Issue by uhrohraggy** [github-changelog-generator/github-changelog-generator#474]
Getting the following error running simple command. Appears due to a new requirement for autoload libraries vs requires needed. See https://github.com/bundler/bundler/pull/4981 

Just wanted to put on your radar if it's not a bundler issue.

running: github_changelog_generator --future-release=v0.1.0
/home/mysys/.rvm/gems/ruby-2.2.5/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:144:in `block in full_require_paths'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `map'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `full_require_paths'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:76:in `contains_requirable_file?'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `block in find_in_unresolved'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `each'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `find_all'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:949:in `find_in_unresolved'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:74:in `require'
	from /home/mysys/.rvm/gems/ruby-2.2.5/gems/bundler-1.14.3/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
	from /home/mysys/.rvm/gems/ruby-2.2.5/gems/bundler-1.14.3/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:144:in `block in full_require_paths'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `map'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/basic_specification.rb:143:in `full_require_paths'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1370:in `add_self_to_load_path'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1283:in `activate'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1314:in `block in activate_dependencies'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `each'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1300:in `activate_dependencies'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1282:in `activate'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /home/mysys/.rvm/rubies/ruby-2.2.5/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /home/mysys/.rvm/gems/ruby-2.2.5/bin/github_changelog_generator:22:in `<main>'
	from /home/mysys/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
	from /home/mysys/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'

**Comment by olleolleolle** [comment]
Thanks for making the link between this library and the Bundler issue. It's a deep issue, for sure. And the rake project did a workaround worth investigating. 

Can you mention which version of Rubygems is used above? `gem --version`.

Can you try running a `gem update --system ` to try the failing thing with a newer Rubygems?

Thanks again, for an interesting report.

**Comment by olleolleolle** [comment]
@uhrohraggy Would the suggested workaround `gem update --system` be within reach for you?

**Comment by thebravoman** [comment]
Similar error from my side:

```
/usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.14.5/lib/bundler/rubygems_ext.rb:45:in `full_gem_path': uninitialized constant Bundler::Plugin::API::Source (NameError)
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb:145:in `block in full_require_paths'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb:144:in `map'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb:144:in `full_require_paths'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb:77:in `contains_requirable_file?'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:949:in `block in find_in_unresolved'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:949:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:949:in `find_all'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:949:in `find_in_unresolved'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:74:in `require'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.14.5/lib/bundler/plugin/api/source.rb:2:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/bundler-1.14.5/lib/bundler/rubygems_ext.rb:45:in `full_gem_path'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb:145:in `block in full_require_paths'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb:144:in `map'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/basic_specification.rb:144:in `full_require_paths'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1370:in `add_self_to_load_path'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1283:in `activate'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
	from /var/lib/jenkins/jobs/Build_fllcasts/workspace/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

```

**Comment by thebravoman** [comment]
```
gem update 
```
was the answer.

**Comment by olleolleolle** [comment]
@uhrohraggy Can you confirm that a `gem update --system` fixes things for you, too?
