### ISSUE TITLE
Use GitHub's GraphQL v4 API

### ISSUE THREAD

**Issue by voxxit** [github-changelog-generator/github-changelog-generator#524]
It seems it [solves a lot of the REST API's rate limiting problems](https://developer.github.com/v4/guides/resource-limitations/#rate-limit) users of this project are encountering with large projects:

> The GraphQL API v4 limit is different from the REST API v3's limit of 5,000 requests per hour for authenticated requests.
> 
> Why are the API rate limits different? With GraphQL, one GraphQL call can replace multiple REST calls. A single complex GraphQL call could be the equivalent of thousands of REST requests. While a single GraphQL call would fall well below the 5,000/hour REST API v3 limit, the query might be just as expensive for GitHub's servers to compute.

Happy to help where I can with this!

**Comment by olleolleolle** [comment]
I am enthusiastic about this good idea.

**Comment by chrislopresto** [comment]
We need this as well and would be happy to collaborate on the necessary updates.

**Comment by olleolleolle** [comment]
I made a branch, and pushed changes to it, which was a start to get "things going". Tomorrow, GitHub has a web-sent live talk about the GraphQL API. (Investigate that to see how it can look.)

I intend to be there, learning bits of how to get this from "cool" to "real".

This move from GitHub's REST API to the GraphQL comes with some knowledge crunching: all the data that we _want_ to receive, and none of the data we don't care about has to be formed into queries - it's not a one-size fits all.
