### ISSUE TITLE
Generating release notes using this

### ISSUE THREAD

**Issue by kabirbaidhya** [github-changelog-generator/github-changelog-generator#549]
Hi,

Is there any easier way to generate release notes using this tool? All we need is to generate the notes in the same format as the change log but only for the issues closed or PRs merged since the last release tag.

It would help a lot while drafting a new release too.

**Comment by olleolleolle** [comment]
I don't know if this works: Have you tried experimenting with the `--since` flag?

**Comment by kabirbaidhya** [comment]
@olleolleolle I tried using `--since`, it worked but it was showing some issues from already released tag too. I tried `--since-tag` as well, but it the result was same. 

Finally, I came across the `--unreleased-only` option, which is what I was looking for. It did work as expected.
```
$ github_changelog_generator --unreleased-only --unreleased-label=<NEXT_RELEASE_TAG>
```

BTW, is it possible to just print the generated output and not write to the `CHANGELOG.md` file? Kind of something like `--dry-run` or similar?

**Comment by lambdafu** [comment]
@kabirbaidhya Under Linux, you can use "-o /dev/stdout" to print it to stdout.

**Comment by skywinder** [comment]
Related to https://github.com/skywinder/github-changelog-generator/issues/56

**Comment by bruce-szalwinski** [comment]
> BTW, is it possible to just print the generated output and not write to the `CHANGELOG.md` file? Kind of something like `--dry-run` or similar?

You can supply `--output` with no file name and it will write to standard out.

**Comment by bruce-szalwinski** [comment]
You could then use [release create](https://cli.github.com/manual/gh_release_create) to create the release notes from the command line!
