### ISSUE TITLE
Add a new line after the credits

### ISSUE THREAD

**Issue by ferrarimarco** [github-changelog-generator/github-changelog-generator#588]
Hi, thanks for this great project.

git complains about a missing newline at the end of the generated CHANGELOG.

Is it possible to add one? Let's discuss. :smile: 

References:
- [Why should text files end with a newline?](https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline)
- [git - No newline at end of file](https://stackoverflow.com/questions/5813311/no-newline-at-end-of-file)

**Comment by skywinder** [comment]
Hi! Let's come back to this update. Seems #627 will fix this. @ferrarimarco can you kindly check, is that PR do, what you mean above?

**Comment by ferrarimarco** [comment]
I'll give it a shot later today :)
