### ISSUE TITLE
Move repo to organisation

### ISSUE THREAD

**Issue by skywinder** [github-changelog-generator/github-changelog-generator#595]
In continue of discussion in #591
https://github.com/skywinder/github-changelog-generator/issues/591#issuecomment-346703143

This project becomes very big and very sociable.
So I accept purpose to move it to organisation.

Here is a naming option:
1. ghcg
2. github-changelog-generator
3. GithubChangelogGenerator

I already book these names of organizations.
Let's a vote for naming altogether. 👍 

I like 1 as a short option and 2 (same name).

cc @olleolleolle @ferrarimarco @awaage

**Comment by olleolleolle** [comment]
I like `2`.

**Comment by ferrarimarco** [comment]
no. `1` and `2` for me

**Comment by ferrarimarco** [comment]
hi all, any updates on this? 😄

**Comment by ferrarimarco** [comment]
Hi @skywinder @olleolleolle any news on this task?

**Comment by skywinder** [comment]
Hey, @ferrarimarco , @olleolleolle 

Let's move on. We are the best! 🥇 

p.s. it's great numbers on the repo to do that 😸 4.4k ⭐️  + 444 🍴 
![image](https://user-images.githubusercontent.com/3356474/38778696-28f291ee-40c6-11e8-8994-6a2974591967.png)

**Comment by skywinder** [comment]
Done! Hello, @github-changelog-generator ! 🎉 
![image](https://user-images.githubusercontent.com/3356474/38778959-132aa672-40ca-11e8-98cb-39770baf7f9e.png)

**Comment by skywinder** [comment]
Now we need to make a logo for the organisation 😉
