### ISSUE TITLE
Specifying since-tag on a PR merge commit can cause that PR to be included

### ISSUE THREAD

**Issue by peppy** [github-changelog-generator/github-changelog-generator#615]
When specifying a `since-tag` that corresponds to a PR merge commit (where the ref of the tag and the merge commit are equal) the PR is unexpectedly included in the changelog.

Tested on latest pre-release build using

`github_changelog_generator -u ppy -p osu-framework --since-tag changelog-20180120 --max-issues 500 --no-issues --release-branch master`

note that the state of this repository may change, let me know if i need to make an isolated test case.

**Comment by hunner** [comment]
This may be fixed in master now.
