### ISSUE TITLE
Version in master branch hangs on MacOS

### ISSUE THREAD

**Issue by lindydonna** [github-changelog-generator/github-changelog-generator#629]
I did the following:
- Pulled down the master branch
- Ran `gem build github_changelog_generator && gem install *.gem`
- Ran `github_changelog_generator` as usual

The `--help` command works, but actual usage just hangs at the `Using these options:` step. See full output below. 

I'm very new to Ruby (learning it on the fly so I could use the change in  https://github.com/skywinder/github-changelog-generator/pull/616), so it's entirely possible I am using an incompatible version of Ruby or one of the dependencies. 

```
$ github_changelog_generator -u orgName -p projectName
Using these options:
^CTraceback (most recent call last):
	11: from /usr/local/bin/github_changelog_generator:23:in `<main>'
	10: from /usr/local/bin/github_changelog_generator:23:in `load'
	 9: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/bin/github_changelog_generator:5:in `<top (required)>'
	 8: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/bin/github_changelog_generator:5:in `new'
	 7: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/lib/github_changelog_generator.rb:28:in `initialize'
	 6: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/lib/github_changelog_generator/parser.rb:29:in `parse_options'
	 5: from /usr/local/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.15.0.pre.rc/lib/github_changelog_generator/options.rb:101:in `print_options'
	 4: from <internal:prelude>:149:in `pp'
	 3: from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/delegate.rb:85:in `method_missing'
	 2: from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/delegate.rb:85:in `call'
	 1: from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/monitor.rb:190:in `mon_enter': Interrupt
```

**Comment by ArtieReus** [comment]
@lindydonna  did you tried to run it from a docker container? then you are free of strange dependencies or incompatibilities...
https://github.com/sapcc/elektra/blob/master/contrib/elektra-changelog-builder/Dockerfile

**Comment by skywinder** [comment]
@lindydonna is this issue still actual?

**Comment by lindydonna** [comment]
@skywinder I didn't try out the docker container, and I'm actually no longer using this tool, unfortunately. I had some very particular requirements, since I had to generate a changelog for multiple repos but integrate them together, so I had to write my own tool :(. I'll close this.

**Comment by felker** [comment]
I also have this issue on macOS. I am not very familiar with Docker so I have been unable to test it there, but I could try it with some guidance.

**Comment by felker** [comment]
Also, this issue occurs with `1.15.0.pre.rc` but not with `1.15.0.pre.beta` for me.
