### ISSUE TITLE
Configure a Docker Automated build

### ISSUE THREAD

**Issue by ferrarimarco** [github-changelog-generator/github-changelog-generator#644]
Hi all.

Let's track the requirements of this feature (now scattered across various PRs and issues).

# Background

1. I opened #591 (Dockerfile and Docker automated builds)
1. #595 (Move repo to organization) was created but took a bit to complete
1. In the meantime #591 was closed by #634 (Remove Docker bits) because I (temporarily) moved the GHCG Docker image under the `ferrarimarco` Docker Hub namespace

# Current Implementation

[ferrarimarco/github-changelog-generator](https://hub.docker.com/r/ferrarimarco/github-changelog-generator/) is backed by [the corresponding GitHub repository](https://github.com/ferrarimarco/docker-github-changelog-generator).

Each commit and Git tag pushed to that repository triggers a build on Docker hub and, if successful, in a new Docker image.

I am currently handling GHCG updates with [Dependabot](https://dependabot.com/). This service automatically creates PRs to update dependencies by looking at [your Gemfile](https://github.com/ferrarimarco/docker-github-changelog-generator/blob/master/Gemfile).

This is the reason why I'm using a separate Gemfile even if we could get rid of it and run commands directly in the Dockerfile.

# Ideas for a more refined implementation

Instead of just installing the updated Gem when available we could provide two kinds of Docker images:
1. One tagged with `latest`: by convention it could point to the latest (successful) build of the master branch. This image is overridden on each commit on master (if the build is ok)
1. One tag for each GHCG release tagged using the same Git tag (i.e. when you release 1.15.0 there will be a corresponding 1.15.0 docker image). This is needed to make production deployment repeatable

Thoughts?

/cc @olleolleolle @skywinder

**Comment by olleolleolle** [comment]
Smart use of dependabot!

**Comment by ferrarimarco** [comment]
@skywinder @olleolleolle did you have the chance to think about this?

**Comment by ferrarimarco** [comment]
@olleolleolle @skywinder let's resume this work if you want since there are a couple of issues related to this. :)

What do you think?

**Comment by thaJeztah** [comment]
Happy to assist as well if needed; one thing I noticed in the old Dockerfile, is that it was fetching the source from inside the Dockerfile; using a `COPY` instead would make sure that the Dockerfile can be built from any branch, and the code always matching the code in that branch

**Comment by ferrarimarco** [comment]
Sounds like a good use case for a multi-staged build actually. So yes, good idea! I'll open a PR for this, since I don't yet have write access here :(

**Comment by ferrarimarco** [comment]
@olleolleolle @skywinder I created an org in Docker Hub but you should approve the access request so I can eventually set up an automated build

**Comment by thaJeztah** [comment]
> since I don't yet have write access here

It's generally good etiquette to use pull requests, even if you have write access 🤗

**Comment by ferrarimarco** [comment]
@thaJeztah I'm a member of this org :)

**Comment by olleolleolle** [comment]
(I don't have admin rights on this repository.)

I also can't see a Docker Hub Organization - does it exist somewhere?

Looking around, I was able to find quite a few people who had set up builds: https://hub.docker.com/search?q=github-changelog-generator&type=image

**Comment by ferrarimarco** [comment]
@olleolleolle I created an org here: https://cloud.docker.com/orgs/githubchangeloggenerator

but need approval to create an automated build...

**Comment by ferrarimarco** [comment]
@olleolleolle @skywinder I need admin access to this repo to proceed further on this.

**Comment by ferrarimarco** [comment]
Done in https://github.com/github-changelog-generator/docker-github-changelog-generator
