### ISSUE TITLE
couldn't generate changelog for organization repos

### ISSUE THREAD

**Issue by medbenmakhlouf** [github-changelog-generator/github-changelog-generator#647]
Hi All,

I am trying to use this tool to generate changelog for a repository  created under organization but it wouldn't work. could you please guide me how can I solve this ?

thank you so much for your help.

**Comment by hunner** [comment]
Hi,

Could you provide some details about what you're trying to do?

**Comment by medbenmakhlouf** [comment]
Hi @hunner ,

thanks for your response, I figure out by : 
- using Organization Name as username
- add token to the command.

it works really fine.

thanks and I am going to close the ticket.
