### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ArtieReus** [github-changelog-generator/github-changelog-generator#649]
Hi there,
there is any plan to roll out a new release? Last one is from October 2017.

Best,
Arturo

**Comment by tphoney** [comment]
Any timeline of getting this merged and released ?

**Comment by ferrarimarco** [comment]
Also needed for #644

**Comment by mesaugat** [comment]
Can we make a pre-release if not the `2.0.0` release? Been waiting for #579 to get released.

**Comment by ferrarimarco** [comment]
#728
