### ISSUE TITLE
Not generating CHANGELOG.md 

### ISSUE THREAD

**Issue by githubvinod** [github-changelog-generator/github-changelog-generator#658]
Not generating CHANGELOG.md 

{:tag1=>nil,
 :tag2=>nil,
 :date_format=>"%Y-%m-%d",
 :output=>"CHANGELOG.md",
 :base=>"HISTORY.md",
 :issues=>true,
 :add_issues_wo_labels=>true,
 :add_pr_wo_labels=>true,
 :pulls=>true,
 :filter_issues_by_milestone=>true,
 :author=>true,
 :unreleased=>true,
 :unreleased_label=>"Unreleased",
 :compare_link=>true,
 :enhancement_labels=>["enhancement", "Enhancement"],
 :bug_labels=>["bug", "Bug"],
 :exclude_labels=>
  ["duplicate",
   "question",
   "invalid",
   "wontfix",
   "Duplicate",
   "Question",
   "Invalid",
   "Wontfix"],
 :issue_line_labels=>[],
 :max_issues=>nil,
 :simple_list=>false,
 :verbose=>true,
 :header=>"# Change Log",
 :merge_prefix=>"**Merged pull requests:**",
 :issue_prefix=>"**Closed issues:**",
 :bug_prefix=>"**Fixed bugs:**",
 :enhancement_prefix=>"**Implemented enhancements:**",
 :git_remote=>"origin",
 :http_cache=>true,
 :cache_file=>"/tmp/github-changelog-http-cache",
 :cache_log=>"/tmp/github-changelog-logger.log",
 :user=>"githubvinod",
 :project=>"devlhealthcareguy",
 :token=>nil}

Traceback (most recent call last):
        19: from C:/Ruby25-x64/bin/github_changelog_generator:23:in `<main>'
        18: from C:/Ruby25-x64/bin/github_changelog_generator:23:in `load'
        17: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `<top (required)>'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/bin/github_changelog_generator:5:in `new'
        15: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `initialize'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator.rb:28:in `new'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `initialize'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/generator/generator.rb:24:in `new'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:34:in `initialize'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `init_cache'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/github_changelog_generator-1.14.3/lib/github_changelog_generator/octo_fetcher.rb:50:in `new'
         8: from C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:387:in `initialize'
         7: from C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:387:in `new'
         6: from C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:673:in `initialize'
         5: from C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:738:in `set_dev'
         4: from C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:744:in `open_logfile'
         3: from C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:748:in `rescue in open_logfile'
         2: from C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:754:in `create_logfile'
         1: from C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:754:in `open'
C:/Ruby25-x64/lib/ruby/2.5.0/logger.rb:754:in `initialize': No such file or directory @ rb_sysopen - /tmp/github-changelog-logger.log (Errno::ENOENT)

**Comment by olleolleolle** [comment]
This Windows Issue has been fixed in the “pre” version.

**Comment by githubvinod** [comment]
Thanks for quick response.it worked for me.  
Need one more help from your side.Am getting **Merged pull requests** only, need commits message along with pull requests.
# Change Log

## [Unreleased](https://github.com/githubvinod/devlhealthcareguy/tree/HEAD)

[Full Changelog](https://github.com/githubvinod/devlhealthcareguy/compare/2018-4-1...HEAD)

**Merged pull requests:**

- Add Staticman data [\#10](https://github.com/githubvinod/devlhealthcareguy/pull/10) ([staticmanapp](https://github.com/staticmanapp))
- Add Staticman data [\#9](https://github.com/githubvinod/devlhealthcareguy/pull/9) ([staticmanapp](https://github.com/staticmanapp))
- Add Staticman data [\#7](https://github.com/githubvinod/devlhealthcareguy/pull/7) ([staticmanapp](https://github.com/staticmanapp))
- Add Staticman data [\#5](https://github.com/githubvinod/devlhealthcareguy/pull/5) ([staticmanapp](https://github.com/staticmanapp))



\* *This Change Log was automatically generated by [github_changelog_generator](https://github.com/skywinder/Github-Changelog-Generator)*

**Comment by olleolleolle** [comment]
@githubvinod Glad to hear that it worked. 🎉 

> commits message along with pull requests.

This is a feature request, not related to this Issue. I'll close this Issue.

**Comment by githubvinod** [comment]
ok...Thanks for your support.
