### ISSUE TITLE
Latest docker image hanging

### ISSUE THREAD

**Issue by sooknarine** [github-changelog-generator/github-changelog-generator#663]
We're trying your github-changelog-generator and appreciate the work you've put into it!  Friendly heads up - the latest docker image appears to be hanging.  The previous 1.14.3 works, though.

This hangs:  `docker run -it --rm -v "$(pwd)":/usr/local/src/your-app ferrarimarco/github-changelog-generator:latest -u skywinder -p ActionSheetPicker-3.0`

This works:  `docker run -it --rm -v "$(pwd)":/usr/local/src/your-app ferrarimarco/github-changelog-generator:1.14.3 -u skywinder -p ActionSheetPicker-3.0`

If you're unable to reproduce and need info or logs from me, let me know.

https://hub.docker.com/r/ferrarimarco/github-changelog-generator/tags/

Thanks!

**Comment by alicon** [comment]
Same issue here

**Comment by arturalbov** [comment]
I've got same issue

**Comment by dongpil** [comment]
Same issue here

**Comment by ferrarimarco** [comment]
@sooknarine is this happening with the non dockerized 1.15.0-rc?

**Comment by sooknarine** [comment]
@ferrarimarco unfortunately I've changed roles and no longer have access to the system that used your tool :( Perhaps @alicon or @arturalbov can try the non dockerized 1.15.0-rc?

**Comment by markmandel** [comment]
Hi! Just wanted to a leave a note this is happening for me too!

I :heart: this project (we're using it over on [Agones](https://agones.dev), but there are some bugs in the 1.14.3 (issues going into the wrong release), that I'm hoping will be fixed in a new release, so I don't have to manually fix them by hand.

Any chance for a new release on this project, and a subsequent push to the new Docker image? It's been a year since release :smile:

**Comment by markmandel** [comment]
If you need a later Docker image that works - I just threw together a Docker image that runs the latest code in Github: https://hub.docker.com/r/markmandel/github-changelog-generator/ 

Mount your code to `/project` in the container, and you are good to go.

**Comment by dskrypko** [comment]
@markmandel 
It seems that the `--release-branch` option doesn't work with your docker image. I tried to generate CHANGELOG for the not `master` branch but got weird CHANGELOG. It didn't match neither `master` branch nor branch I specified.

**Comment by markmandel** [comment]
@dskrypko 
My image may not be up to date with what is in github - it's not an automatic rebuild.

But you can likely take the Dockerfile and create your own, up to date image from it!

**Comment by ferrarimarco** [comment]
The version that is currently tagged as a docker image is in sync with the latest GCG version.

As soon as a new version is released, I'll update the image.

Actually since we saw no version in a few months, I may release an updated "latest" image pointing to the current master.

**Comment by ferrarimarco** [comment]
BTW we are tracking this issue in #644
