### ISSUE TITLE
Exclude related issues or PR's to avoid redundancy 

### ISSUE THREAD

**Issue by skywinder** [github-changelog-generator/github-changelog-generator#67]
This topic is described here: [nodegit/nodegit/pull/465](https://github.com/nodegit/nodegit/pull/465).

> many of those PRs are fixing things introduced in the release, so it seems odd to include them in the changelog.

and:

> That would be great, since we could exclude issues fixed that were introduced in the same release

**Comment by skywinder** [comment]
To test: 
https://github.com/skywinder/changelog_test/issues/14
https://github.com/skywinder/changelog_test/issues/15
https://github.com/skywinder/changelog_test/issues/13

**Comment by skywinder** [comment]
Sadly, but I don't know, how to detect, which PR close specific Issue. There is only info about hash of commits in the events details. Is someone knows, how to detect it - let me know please.

**Comment by pnorman** [comment]
> Sadly, but I don't know, how to detect, which PR close specific Issue. There is only info about hash of commits in the events details. Is someone knows, how to detect it - let me know please.

In the web UI you can see how an issue was closed, e.g. skywinder/changelog_test#12 shows it was closed in skywinder/changelog_test#13 and skywinder/changelog_test#14 shows it was closed in https://github.com/skywinder/changelog_test/commit/decfe840d1a1b86e0c28700de5362d3365a29555

**Comment by skywinder** [comment]
I'm not working with web UI. I'm using https://developer.github.com/v3/activity/events/ to fetch specific actions for PR and issues (such as `merged`,`closed`,`referenced` actions and so on). I check all properties for `referenced` but there is no any field, that can help determinate, is it just reference to issue, or reference, that close another issue - that is a problem.

**Comment by pnorman** [comment]
Yes, obviously you're using the API, but I would have expected the information on the web UI to be available through the API.

I checked both events and the single issue get for issue 14, and found no reference to why it is closed.

I'd suggest raising this with Github, as it seems odd for the issue to say through the web, but not through the API.

**Comment by skywinder** [comment]
@pnorman seems reasonable. I will  send the a message.

**Comment by skywinder** [comment]
Also duplicate message to support here:

>Hello, @github. In continue of our discussion here,
I would like to ask, is there any way to check from IssuesEvent (https://developer.github.com/v3/activity/events/types/#issuesevent), which issue of commit closes this issue.
i.e. if I specify magic phrase in the Issue `#43` like "Close `#42`" and close this issue, then `#42` is also closed the same time. So, is it possible to detect from api for IssuesEvent `#42` that it closed by `#43`?

**Comment by skywinder** [comment]
Got answer:

>Hi Petr,
That information is not available via the API currently. I agree that would be helpful, and it's already on our wishlist, but I can't promise when it might be implemented.
I hope this answers your question, but please let me know if there's anything else.

I leave this issue open, since it's really appreciated behaviour. Hope, someone could find solution for this feature with some workaround.
