### ISSUE TITLE
[DOC] Explain new Labels and Summary Section support in README

### ISSUE THREAD

**Issue by olleolleolle** [github-changelog-generator/github-changelog-generator#678]
Update README.md 

- with **new labels support** and
- examples of usage of summary section

See #654

**Comment by olleolleolle** [comment]
Thanks, this is a good start, would you begin a PR with that content? (I can't copy-and-paste the raw Markdown from here.)

**Comment by olleolleolle** [comment]
Actually, I _can_ see the raw Markdown!

**Comment by mob-sakai** [comment]
Thanks for your PR!

**Comment by skywinder** [comment]
You're awesome, guys! 🎉

**Comment by edusantana** [comment]
I was trying to use it, but it is not working. Can you share a project that uses it?

**Comment by edusantana** [comment]
I looking at https://github.com/voxpupuli/puppet-extlib/blob/master/Rakefile

**Comment by mob-sakai** [comment]
Hi @edusantana 
Did you install `github-changelog-generator` with `gem install`?
It is a too old version to use summary section.
```
$ github_changelog_generator  -v
Version: 1.14.3
```

Use `gem specific_install` instead of `gem install`.

`gem specific_install git@github.com:github-changelog-generator/github-changelog-generator.git -b master`

**Comment by edusantana** [comment]
As you [see here](https://github.com/abntex/limarka/blob/58ab4804af11aa0f05a706a36441124477d5cf63/limarka.gemspec#L28) a use it like this:

```ruby
Gem::Specification.new do |spec|
  #...
  spec.add_development_dependency "github_changelog_generator"
  #...
end
```

My workaround was to use it [at the Gemfile as well](https://github.com/abntex/limarka/blob/58ab4804af11aa0f05a706a36441124477d5cf63/Gemfile#L4), but I don't like it.

At what version this summary option was added?

**Comment by mob-sakai** [comment]
1.15.0, but it has not been released yet.
