### ISSUE TITLE
[question] Generate changelog with local tag before its pushed

### ISSUE THREAD

**Issue by rockandska** [github-changelog-generator/github-changelog-generator#697]
Hi,

Changelog-generator use the tags to generate his changelog.
Does it works if the tag is not already pushed to github but only local ?
I would like to push the release with his changelog in the same step without the need to push the tag then generate the changelog.

Regards,

**Comment by mob-sakai** [comment]
Use `--future-release [RELEASE-VERSION]` option to generate the CHANGELOG before tagging.
It will replace "Unreleased" section with "[RELEASE-VERSION]" section.
This is a suitable way for the development flow that generates CHANGELOG before each releasing (such as git-flow).

**Comment by NathanUrwin** [comment]
The `--future-release` option doesn't seem to create a **Merged pull requests:** for me...

**Comment by kriszrtina** [comment]
K
