### ISSUE TITLE
Re-write/implement this awesome piece of software in Go!

### ISSUE THREAD

**Issue by moorara** [github-changelog-generator/github-changelog-generator#714]
Anyone interested in re-writing the best GitHub changelog generator in the world (a.k.a github_changelog_generator) in Go?

I am craving for having this changelog generator as a single binary and also importing it in my releaser tool and using it programmatically!

**Comment by maierlars** [comment]
In such a case german children would say: "Immer der, der fragt!"

**Comment by NathanUrwin** [comment]
![Screen Shot 2019-05-16 at 9 08 41 PM](https://user-images.githubusercontent.com/13526277/57898468-cf132080-781e-11e9-9304-0ac6bd48b807.png)

**Comment by ferrarimarco** [comment]
While this is potential source of fun, it's out of scope :)

**Comment by moorara** [comment]
@maierlars @NathanUrwin OK, it took me a while until I understand what does "Immer der, der fragt!" mean! 😉 

Here it is: https://github.com/moorara/changelog
