### ISSUE TITLE
Could we publish the latest version to gem?

### ISSUE THREAD

**Issue by huan** [github-changelog-generator/github-changelog-generator#722]
when I use `$ gem install github_changelog_generator` the code is quite outdated.

Could we publish the latest code to gem so that we could install the latest code from here?

Thanks!

**Comment by ericyahhh** [comment]
@huan You can at least use the pre-release version `v1.15.0` which has a lot of bug fixes

`gem install github_changelog_generator --pre`

**Comment by ferrarimarco** [comment]
Tracking this in #728

**Comment by huan** [comment]
I have to modify the `lib/github_changelog_generator/octo_fetcher.rb` with `MAX_THREAD_NUMBER = 10` to include the #661 fix by hand now.
