### ISSUE TITLE
Releasing 1.15.0

### ISSUE THREAD

**Issue by ferrarimarco** [github-changelog-generator/github-changelog-generator#728]
Hi @skywinder , @olleolleolle 

We have a number of issues asking for a new release (#722, #649) and issues that are blocked because they need a new release (#717).

I think we should release the 1.15.0 final, pointing to the latest master ([the latest commits](https://github.com/github-changelog-generator/github-changelog-generator/releases/tag/v1.15.0.pre.rc) add nothing major).

I think this is a must to start cleaning the issue backlog. We want to ask the issue reporters to try with the latest released version. Eventual fixes will be handled by releasing minor versions.

Thoughts?

Questions:

1. Do you have a doc somewhere that explains the release process?

Tasks:

1. Version bump  to 1.15.0
1. Create a git tag
1. Upload the gem

**Comment by ekohl** [comment]
Would this be a release of current master? https://github.com/github-changelog-generator/github-changelog-generator/pull/641 was arguing that it needed to be a major version bump. That said, :+1: for a new release.

**Comment by ferrarimarco** [comment]
I had a look at the commit since the last pre-release and are mostly bug fixes or docs addition.

What made you think we need to bump to release the current master? Any particular commit/PR?

Thanks!

**Comment by ekohl** [comment]
The open PR (not mine) has argumentation. I don't have a strong opinion other than that it's time for a new release :)

**Comment by ferrarimarco** [comment]
I'm not going to merge them before releasing 1.15.0 :)

**Comment by huan** [comment]
When could we release the v1.15? Or I have to use a workaround like `gem install github_changelog_generator --pre` to prevent hitting the threshold of Github API rate-limitation.

**Comment by ferrarimarco** [comment]
There is work undergoing to release it in the coming days!

**Comment by ferrarimarco** [comment]
The repo is ready for the 1.15.0. I need to build and release the gem, and we're set!

**Comment by liuxuan30** [comment]
when can you release for gem? can't wait

**Comment by ferrarimarco** [comment]
Released
