### ISSUE TITLE
Warning about Project_card_events API

### ISSUE THREAD

**Issue by ZedThree** [github-changelog-generator/github-changelog-generator#773]
I get a lot of the following messages:

> WARNING: The preview version of the Project_card_events API is not yet suitable for production use.
You can avoid this message by supplying an appropriate media type in the 'Accept' request
header.

It sounds like it will resolve itself in time, but at the minute it's spamming the terminal.

**Comment by digglife** [comment]
The warning is generated by Octokit module ,we can avoid it by adding accept option for relevant requests(`issue_events` in this case). I submitted a fix PR, which is now pending on maintainer's review.

**Comment by skywinder** [comment]
Oh, thank you very much, @digglife ! Much appreciated! 

---

ps.
BTW, I would like to support from Tidelift this project. (about 50$/month) - I would be glad to send this money for to supporters.
If you would like to help with resolving issues and PR - please send me message, we can discuss this option.
