### ISSUE TITLE
Footer message that keeps replicating

### ISSUE THREAD

**Issue by shinyaohtani** [github-changelog-generator/github-changelog-generator#787]
Even if a footer message has already been added to the file specified in config.base, if I execute the script to add a change log for the newly developed part, a footer message will be added one by one every time.

- before
  ```changelog.md
  This Changelog was automatically generated by...
  ```
- after
  ```changelog.md
  This Changelog was automatically generated by...
  This Changelog was automatically generated by...
  ```
- after 2 times (keep replicating infinitely)
  ```changelog.md
  This Changelog was automatically generated by...
  This Changelog was automatically generated by...
  This Changelog was automatically generated by...
  ```

Maybe, this code doesn't work:
https://github.com/github-changelog-generator/github-changelog-generator/blob/af4e869d7d55326fe1c81842b7a2bbe4fc71be1e/lib/github_changelog_generator/generator/generator.rb#L62

- Environment
  - macOS Catalina (10.15.4)
  - project: [giturl](https://github.com/shinyaohtani/giturl/tree/master/)
  - ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]

**Comment by shinyaohtani** [comment]
```ruby
credit_line = "\n\n\\* *This..."
```

In order to find the exactly same expression, "*" should be escaped as "\*"

```ruby
> "\\*".sub(/\\\*/,'ok')
=> "ok"
```

**Comment by olleolleolle** [comment]
@shinyaohtani Would you like to make a PR with a fix and a test?

**Comment by shinyaohtani** [comment]
@olleolleolle ok, I'll make PR.

**Comment by shinyaohtani** [comment]
@olleolleolle I sent pull request about "replicating template messages". Would you please review when you have time?
PR: #794
