### ISSUE TITLE
configure_sections needs better examples

### ISSUE THREAD

**Issue by bruce-szalwinski** [github-changelog-generator/github-changelog-generator#923]
The documentations is not clear what the value for `configure_sections` parameter should be.  Looking through the [code](https://github.com/github-changelog-generator/github-changelog-generator/blob/8525969c7c4e673d14f62e90b55ca9e39b4197ef/lib/github_changelog_generator/generator/entry.rb#L72), it appears that it wants a JSON document but the docs don't expose what the keys of this document should be.  Thru some poking around, I came up with this format which works.

```
{
    "enhancements": {
        "prefix": ":sparkles: Enhancements",
        "labels": [
            "enhancement",
            "feat"
        ]
    },
    "bugs": {
        "prefix": ":bug: Bug Fixes",
        "labels": [
            "fix"
        ]
    },
    "refactor": {
        "prefix": ":hammer: Refactor",
        "labels": [
            "refactor"
        ]
    },
    "books": {
        "prefix": ":books: Documentation",
        "labels": [
            "docs"
        ]
    },
    "style": {
        "prefix": ":gem: Style",
        "labels": [
            "style"
        ]
    },
    "performance": {
        "prefix": ":rocket: Performance",
        "labels": [
            "perf",
            "performance"
        ]
    },
    "test": {
        "prefix": ":heart: Test",
        "labels": [
            "test"
        ]
    },
    "build": {
        "prefix": ":package: Build",
        "labels": [
            "build",
            "ci"
        ]
    },
    "chore": {
        "prefix": ":wrench: Chore",
        "labels": [
            "chore"
        ]
    }
}
```

The config reader doesn't support multi-line config (ala yaml or json), so I ended up having to minify this document into one line which makes it cumbersome to edit.

I guess a second issue would be to convert the config reader to something other than `key=value`

**Comment by bruce-szalwinski** [comment]
Found what I was looking for at https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples

**Comment by olleolleolle** [comment]
@bruce-szalwinski Could you make a PR adding a link to that place? I mean, to help Bruce-in-the-past find the content.
