### ISSUE TITLE
Allow passing location of configuration file to ParseFile

### ISSUE THREAD

**Issue by kzu** [github-changelog-generator/github-changelog-generator#925]
It's quite common nowadays to keep github-related files under the `.github` directory in a repository, to keep the root file listing cleaner. 

I've been trying to figure out a way to pass the path to the `.github-changelog-generator` somehow, which [seems to be supported](https://github.com/github-changelog-generator/github-changelog-generator/blob/master/lib/github_changelog_generator/parser_file.rb#L26) but not [actually used](https://github.com/github-changelog-generator/github-changelog-generator/blob/master/lib/github_changelog_generator/parser.rb#L14) or surfaced. 

I think it would be good if passing the file path were supported and documented as part of the [advanced examples](https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples) doc.

Thanks!

**Comment by olleolleolle** [comment]
Right, good dig!

Would you like to improve the implementation and write a test for it?

**Comment by kzu** [comment]
He, would love to, but would have to learn ruby from scratch too as part of that. Seems like a large-ish endeavor. Maybe some other kind soul will volunteer 🙏

**Comment by anakinj** [comment]
I think this is already supported with the `--config-file` parameter that is documented in referenced page.

**Comment by kzu** [comment]
Ha! I see you *[added](https://github.com/github-changelog-generator/github-changelog-generator/commit/90051d143e34f39a4f34ede7ee9b2a3f42040327#diff-62be65b915f9226d01086a712f7b1c210468cffb8833038391967689bde68579)* that support *after* I reported it @anakinj 😉
