### ISSUE TITLE
Can't install it.

### ISSUE THREAD

**Issue by Ayfri** [github-changelog-generator/github-changelog-generator#933]
**Describe the bug**
I can't install this gem, I'm getting this every time:
```ruby
ERROR:  Could not find a valid gem 'github_changelog_generator' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)
```
**To Reproduce**
I just do `sudo gem install github_changelog_generator`.

**Versions:**
 - OS: Ubuntu 20.04.1 LTS
 - Ruby: ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
 - Gem: 3.1.2

**Additional context**
This is the first time I use/install ruby.

**Comment by olleolleolle** [comment]
👋 Hello! This does sound like a _RubyGems_ issue with your environment.

Here is a RubyGems Issue which describes someone having this kind of network access trouble: 
https://github.com/rubygems/rubygems/issues/2253#issuecomment-432111545

Hope this helps! I will close this Issue, but please let me know with a comment if you were able to get anything working! 👋
