### ISSUE TITLE
Release 1.16: If you give a specifc name to the GitHubChangelogGenerator::RakeTask, it breaks.

### ISSUE THREAD

**Issue by mfortin** [github-changelog-generator/github-changelog-generator#942]
**Describe the bug**
Since 1.16 was released, rake is broken. See full trace here https://travis-ci.org/github/dev-sec/chef-os-hardening/jobs/763925521
```
$ bundle exec rake kitchen
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/home/travis/build/dev-sec/chef-os-hardening/vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.16.0/lib/github_changelog_generator/task.rb:34:in `initialize'
/home/travis/build/dev-sec/chef-os-hardening/vendor/bundle/ruby/2.6.0/gems/github_changelog_generator-1.16.0/lib/github_changelog_generator/task.rb:34:in `initialize'
/home/travis/build/dev-sec/chef-os-hardening/Rakefile:57:in `new'
/home/travis/build/dev-sec/chef-os-hardening/Rakefile:57:in `<top (required)>'
/home/travis/build/dev-sec/chef-os-hardening/vendor/bundle/ruby/2.6.0/gems/rake-13.0.3/exe/rake:27:in `<top (required)>'
/home/travis/.rvm/rubies/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
/home/travis/.rvm/rubies/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
The command "bundle exec rake kitchen" exited with 1.
cache.2
```

**To Reproduce**
Create Rakefile with
```
begin
  # read version from metadata
  metadata = Chef::Cookbook::Metadata.new
  metadata.instance_eval(File.read('metadata.rb'))

  # build changelog
  require 'github_changelog_generator/task'
  GitHubChangelogGenerator::RakeTask.new :changelog do |config|
    config.future_release = "v#{metadata.version}"
    config.user = 'dev-sec'
    config.project = 'chef-os-hardening'
  end
rescue LoadError
  puts '>>>>> GitHub Changelog Generator not loaded, omitting tasks'
end
```
Run `bundle exec rake kitchen`

**Expected behavior**
No error. Expected documentation about required changes, if any.

**Screenshots**

**Additional context**
1.15.2 was working OK.

**Comment by olleolleolle** [comment]
@mfortin What happens to your rake task if you attempt to leave out the `:changelog` argument (which is the default, according to https://github.com/github-changelog-generator/github-changelog-generator/blob/master/lib/github_changelog_generator/task.rb#L35 ) ?

**Comment by olleolleolle** [comment]
@mfortin Does the change in the linked PR change things for you?

**Comment by kennyadsl** [comment]
I have the same issue and removing the `super` call as done #943 seems to fix it.

**Comment by mfortin** [comment]
removing `:changelog` seems to be OK.

**Comment by mfortin** [comment]
I believe the right solution is to remove the `super` call, as it is backward compatible

**Comment by kennyadsl** [comment]
Maybe you can keep the `super` call only when there's no argument passed and emit a deprecation warning for who is still using it if you want to remove it in the future.

**Comment by olleolleolle** [comment]
@kennyadsl Calling `super()` allows it work, too.

**Comment by kennyadsl** [comment]
Right!

**Comment by mfortin** [comment]
@olleolleolle are you planning on creating a new release today ?
