### ISSUE TITLE
Unable to run, undefined method `include?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by emilyjablonski** [github-changelog-generator/github-changelog-generator#954]
**Describe the bug**
I am unable to produce a changelog at all with the command `github_changelog_generator -u repo-namespace -p project-name --max-issues 50`, and get the below output

Found 36 tags
Fetching tags dates: 36/36
Sorting tags...
Received issues: 100
Pull Request count: 554
Filtered pull requests: 59
Filtered issues: 35
Fetching events for issues and PR: 94
Fetching closed dates for issues: 94/94
Traceback (most recent call last):
	7: from /Users/emilyjablonski/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/async-1.29.0/lib/async/task.rb:263:in `block in make_fiber'
	6: from /Users/emilyjablonski/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator.rb:55:in `block in compound_changelog'
	5: from /Users/emilyjablonski/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator.rb:152:in `fetch_issues_and_pr'
	4: from /Users/emilyjablonski/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator_fetcher.rb:49:in `add_first_occurring_tag_to_prs'
	3: from /Users/emilyjablonski/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator_fetcher.rb:105:in `associate_release_branch_prs'
	2: from /Users/emilyjablonski/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator_fetcher.rb:105:in `reject'
	1: from /Users/emilyjablonski/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator_fetcher.rb:107:in `block in associate_release_branch_prs'
/Users/emilyjablonski/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.1/lib/github_changelog_generator/generator/generator_fetcher.rb:201:in `sha_in_release_branch': undefined method `include?' for nil:NilClass (NoMethodError)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.7

My only thought is that this is a Ruby version issue but I just re-installed Ruby?

**Comment by olleolleolle** [comment]
It's a defect with this software. Does it happen with the most current code (unreleased)?

**Comment by emilyjablonski** [comment]
I believe so, I just installed it yesterday with `gem install github_changelog_generator`

**Comment by emilyjablonski** [comment]
`def sha_in_release_branch(sha)
      branch = @options[:release_branch] || @fetcher.default_branch
      shas_in_branch = @fetcher.commits_in_branch(branch)
      shas_in_branch.include?(sha)
end`
Here is the specific function for me that appears to be failing, as if commits is null?

**Comment by olleolleolle** [comment]
@emilyjablonski Ah, oh, I meant the other way around, if you were to use the unreleased code, can you reproduce the issue?

I think there are mentions of the gem specific_install in this bug tracker. That's one way of test-running unreleased code.

**Comment by dusan-dragon** [comment]
I tried it with specific_install and it throws same error :/

**Comment by dusan-dragon** [comment]
Also note that it has just issues with some specific PRs I guess, because on some repos 1.16.1 works and on some it does not.

**Comment by olleolleolle** [comment]
@dusan-dragon Hi! I made a change, after reading the code, and merged it. Could you re-run your check, using specific_install, to see if it had any effect?

**Comment by dusan-dragon** [comment]
@olleolleolle I can confirm that with newest master the issue is gone. Looking forward for new release 🎉

**Comment by olleolleolle** [comment]
@dusan-dragon Appreciate the support. v1.16.2 is on RubyGems.org now.
