### ISSUE TITLE
front-matter does not allow break lines?

### ISSUE THREAD

**Issue by jorgecarleitao** [github-changelog-generator/github-changelog-generator#962]
**Describe the bug**

When the changelog is created with a section `front-matter=For older versions, see X`, the output is

```
For older versions, see X# Changelog
```
i.e. there is no break line.

Is there a way to fix this as a user, or is it a bug?

**Comment by olleolleolle** [comment]
I would call it a bug, one which perhaps occurs for users that do not use the Rake task way of configuration - since there they have the full power of Ruby - they can add "\n" as they want to in their configuration line.

Are you using the configuration file way of configuring, here? (Asking to narrow down where to try finding the current behavior.)

Proposed Workaround 1: use a Rakefile and configure the task with Rake.

**Comment by jorgecarleitao** [comment]
I am using the docker image and the configuration file `.github_changelog_generator`.

**Comment by olleolleolle** [comment]
@jorgecarleitao 

An example input in the field would be something like

```
github_changelog_generator --front-matter '{"hello":"world"}'
```

which would turn into a YAML preamble aka front-matter.

If you try adding that single option as a CLI configuration option, does that generate a YAML frontmatter?

**Comment by jorgecarleitao** [comment]
Thanks a lot @olleolleolle for your fast reply and help.

So, that seems to raise an error instead:

```
/usr/local/bundle/gems/github_changelog_generator-1.16.2/lib/github_changelog_generator/argv_parser.rb:76:in `block (2 levels) in parser': undefined method `to_yaml' for {"hello"=>"world"}:Hash (NoMethodError)
Did you mean?  to_a
```

command:

```bash
docker run -it --rm -e CHANGELOG_GITHUB_TOKEN=$CHANGELOG_GITHUB_TOKEN \
    -v "$(pwd)":/usr/local/src/your-app \
    githubchangeloggenerator/github-changelog-generator \
    --user apache \
    --project arrow-rs \
    --since-commit 2021-04-20 \
    --future-release 4.0.1 \
    --front-matter '{"hello":"world"}'
```

**Comment by olleolleolle** [comment]
@jorgecarleitao That's good news, since we can change the to_yaml to a YAML.generate implementation instead.

**Comment by olleolleolle** [comment]
The bug fix has been released as v1.16.3.

**Comment by jorgecarleitao** [comment]
wow, thank you so much for such a quick reaction, fix and release ❤️

Much appreciated, @olleolleolle !

**Comment by jorgecarleitao** [comment]
Does this release triggered the release of a new docker image?

**Comment by olleolleolle** [comment]
@jorgecarleitao I don't think that it does. I don't know exactly how that works, though!
