### ISSUE TITLE
`gsub!': can't modify frozen String (FrozenError) causing changelog generator exiting with error code 1

### ISSUE THREAD

**Issue by kian2attari** [github-changelog-generator/github-changelog-generator#977]
**Describe the bug**

Recent runs of the action have suddenly started failing with the following error:

<img width="1256" alt="Screen Shot 2021-08-10 at 8 28 35 PM" src="https://user-images.githubusercontent.com/24510265/128951753-98a9c32c-8a1d-46bc-a537-251780084f1c.png">

<img width="984" alt="Screen Shot 2021-08-10 at 8 28 02 PM" src="https://user-images.githubusercontent.com/24510265/128951714-32bf60b1-278c-44a2-b265-0ddfe074a81d.png">

For reference, here is the error text:

```
/Users/runner/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.4/lib/github_changelog_generator/generator/generator.rb:160:in `gsub!': can't modify frozen String (FrozenError)
Associating PRs with tags: 9/188
	from /Users/runner/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.4/lib/github_changelog_generator/generator/generator.rb:160:in `remove_old_fixed_string'
Associating PRs with tags: 10/188
	from /Users/runner/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/github_changelog_generator-1.16.4/lib/github_changelog_generator/generator/generator.rb:63:in `block in compound_changelog'
Associating PRs with tags: 11/188
	from /Users/runner/hostedtoolcache/Ruby/2.6.8/x64/lib/ruby/gems/2.6.0/gems/async-1.30.1/lib/async/task.rb:260:in `block in make_fiber'
```

This is my partial config file, it was working perfectly

```
          unreleased-label=New features since previous release **${{ env.LATEST_RELEASE_TAG }}**
          output=CHANGELOG.md
          configure-sections={"enhancements":{"prefix":"###  🚀  Enhancements:","labels":["enhancement"]},"bugs":{"prefix":"###  🐛  Bug fixes:","labels":["bug"]},"security":{"prefix":"###  🔒  Security:","labels":["security"]},"documentation":{"prefix":"###  📜  Documentation:","labels":["documentation"]},"tests":{"prefix":"###  🧪  Tests:","labels":["tests"]}}
          compare-link=true
          unreleased-only=true
          date-format=%m/%d/%Y
          header-label=<!-- Changelog -->
          pr-label=### ➕  Other merged pull requests 
          issues=false
          issues-wo-labels=false
```

**To Reproduce**
This is currently happening on a private repo but I'll update this once I have a test repo running with the issue

**Comment by olleolleolle** [comment]
Yes, this is a bug, but MAYBE you can work around it by disabling the --enable-frozen-string-literal option, perhaps by:

`RUBYOPT=--disable-frozen-string-literal`

**Comment by kian2attari** [comment]
The issue only appears if you set `unreleased-only` to true

**Comment by olleolleolle** [comment]
@kian2attari This issue is a defect that GitHub Changelog Generator expects strings to be mutable, when they _may_ be immutable, in its own code. There were issues in dependent gems, too, but this project has a few of these problems.

**Comment by adangel** [comment]
For me, this happened with `--unreleased-only` and when there where no closed issues/pull requests after the last release.
See #981 for a fix.
